# Aplicação 1: dependência

@mayrink2020 apresenta como o modelo CAR pode ser usado para criar estruturas de dependência tanto nas cargas quanto nos escores. O esquema CAR preconiza que se $\{Z(A_i)\}_i$ é um Campo Markoviano de forma

$$
Z(A_i) \mid Z(A_{(-i)}) \sim 
N\left(
\mu_i + \sum_{j=1}^n c_{ij}\big(Z(A_j) - \mu_j\big), \ \tau_i^2
\right),
$$
Então a estrutura de covariância de $Z = \bigr(\ Z(A_1), \dots, Z(A_n) \ \bigr)$ é dada por

$$\text{Cov}(Z) = \bigr[D(W) - \rho W\bigr]^{-1},$$
em que $W$ é a matriz de vizinhanças e $D(W)$ uma matriz diagonal com as somas das linhas de $W$ e $\rho$ depende das escolhas dee $c_{ij}$ e é tal que $|\rho|<1$.

$$
(\alpha_{\emptyset_k}, \alpha_{0k})^T \sim 
\text{Normal}_n\big(0, B_k\big),
\quad
B_k =
\begin{bmatrix}
B_{k,11} & B_{k,12} \\
B_{k,21} & B_{k,22}
\end{bmatrix}.
$$

$$\alpha_{\emptyset k} \mid \alpha_{0k}\ \sim\ 
N_{|G_k \cup G_E|} \big( 0, B_{\emptyset k} \big),$$

em que $B_{\emptyset k} = B_{k,11} - B_{k,12} B_{k,22}^{-1} B_{k,21}$ e $G_k$ e $G_E$ é o conjunto de índices das variáveis associadas aos grupos $k$ e extra, respectivamente.

Os escores da aplicação de @mayrink2020 representam anos. Os autores fazem uma estrutura de vizinhança entre os tempos de modo que $t_i$ é vizinho de $t_{i-1}$ e $t_{i+1}$.

$$\lambda_{i, \cdot} \sim N_m\Bigr(0, v_\lambda \bigr[ D(W_\lambda) - \rho_\lambda W_\lambda \bigr]^{-1}\Bigr).$$
$v_\lambda$ é adicionado por questões de identificabilidade, de modo a controlar os elementos da diagonal da matriz CAR.