project:
  type: book

lang: pt

book:
  title: "Aplicações de Análise Fatorial Bayesiana"
  author: "Carlos de Moura"
  date: "6/30/2026"
  chapters:
    - index.qmd
    - qmd/basics.qmd
    - qmd/dependencia.qmd
    - qmd/genes.qmd

bibliography: qmd/references.bib
csl: apa-5th-edition.csl
nocite: |
  @*

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
  warning: false
  message: false
